-- ============================================================================
-- Replace the mission bank with a curated set of GENERAL spontaneous quests,
-- organised by difficulty only (no themed categories). Seeded from the
-- product owner's examples and expanded — 25 per tier, 100 total.
-- ============================================================================

-- A single flat "general" category.
insert into mission_categories (slug, name, description, icon, color, sort_order)
values ('general', 'כללי', 'משימות ספונטניות כלליות', 'sparkles', '#7C5CFF', 0)
on conflict (slug) do update set name = excluded.name, color = excluded.color;

-- Out with the old bank (cascades to old assignments/submissions — pre-launch).
delete from missions;

insert into missions
  (title, description, category_id, difficulty, base_points, xp_reward, proof_types, min_mood, points_rationale)
values
('צלמו משהו כחול שנמצא לידכם','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו את עצמכם נותנים כיף למישהו','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{video}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו סלפי רנדומלי וכתבו בכיתוב: «רק בינינו»','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו את האוכל האחרון שאכלתם','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו משהו שגורם לכם לחייך','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('שלחו הודעת «תודה» למישהו וצלמו את המסך','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו סלפי עם הפרצוף הכי מצחיק שלכם','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו את הנעליים שאתם נועלים עכשיו','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו משהו אדום בחדר','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו את השמיים בדיוק כמו שהם נראים עכשיו','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('חבקו מישהו וצלמו סלפי יחד','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו את הכוס או הספל שאתם שותים ממנו','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו סלפי עם אגודל למעלה','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('כתבו מילה טובה על פתק וצלמו אותו','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו את הדבר האהוב עליכם בחדר','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו את עצמכם עושים לב עם הידיים','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו סלפי עם מישהו שנמצא לידכם','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו חפץ ישן שיש לכם כבר שנים','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('שלחו «בוקר טוב» למישהו שלא דיברתם איתו מזמן וצלמו מסך','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו את הנוף מהחלון שלכם','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו את עצמכם קורצים למצלמה','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{video}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו משהו צהוב','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו סלפי במקום האהוב עליכם בבית','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צלמו את המשקה האהוב עליכם','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{photo}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('הרימו כוסית «לחיים» וצלמו את עצמכם','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'easy',2,10,'{video}','not_today','משימה קלה ומהירה — 2 נקודות.'),
('צאו מהבית וצלמו סלפי בחוץ','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{photo}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('למדו קסם קטן וצלמו את עצמכם עושים אותו','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{video}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('צלמו את השקיעה היום','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{photo}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('הכינו מטוס נייר וצלמו אותו עף','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{video}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('הזמינו חבר לפגישה ספונטנית וצלמו סלפי יחד','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{photo}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('גלו מקום חדש בשכונה שלא הכרתם וצלמו אותו','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{photo}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('למדו מילה בשפה חדשה ואמרו אותה במצלמה','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{video}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('צלמו את עצמכם מנסים משהו בפעם הראשונה','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{video}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('צאו להליכה של 15 דקות וצלמו משהו יפה בדרך','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{photo}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('שבו בבית קפה לבד וצלמו את הרגע','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{photo}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('צלמו את הזריחה או השקיעה עם מישהו','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{photo}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('התחילו שיחה עם זר ואמרו במצלמה איך היה','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{video}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('הכינו לעצמכם משקה מיוחד וצלמו אותו','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{photo}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('צלמו את עצמכם רוקדים 15 שניות','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{video}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('בקרו במקום שלא הייתם בו שנה וצלמו סלפי','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{photo}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('השאירו פתק חיובי לזר וצלמו איפה הנחתם אותו','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{photo}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('טעמו אוכל שמעולם לא ניסיתם וצלמו את התגובה','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{video}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('שירו חלק משיר מול המצלמה','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{video}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('עשו משהו נחמד למישהו בלי שביקש וצלמו','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{video}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('צלמו 3 תמונות של אותו מקום מזוויות שונות','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{photo}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('התקשרו למישהו שאתם אוהבים וצלמו סלפי בזמן השיחה','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{photo}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('למדו לצייר משהו פשוט ב-5 דקות וצלמו','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{photo}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('עשו משהו שמפחיד אתכם קצת וצלמו סרטון אחרי','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{video}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('צאו לרכיבה קצרה או קורקינט וצלמו נקודה בדרך','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{photo}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('הכינו ארוחה קטנה למישהו וצלמו אותה','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'medium',5,20,'{photo}','a_little','דורשת קצת יציאה מהשגרה — 5 נקודות.'),
('בשלו מנה שמעולם לא הכנתם וצלמו את הארוחה','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('רוצו 2 קילומטר וצלמו סלפי בסיום','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('ציירו ציור יפה שהשקעתם בו וצלמו אותו','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('עשו אימון של 20 דקות וצלמו את עצמכם אחרי','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{video}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('הגיעו ל-8,000 צעדים היום וצלמו את מונה הצעדים','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('הכינו קינוח מאפס וצלמו אותו','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('עשו 50 שכיבות סמיכה (בכמה סטים) וצלמו סרטון','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{video}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('בלו שעה שלמה בלי הטלפון וצלמו סלפי אחרי','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('הפכו פינה בבית — צלמו לפני ואחרי','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('למדו לנגן או לשרוק לחן שלם וצלמו סרטון','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{video}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('כתבו מכתב אמיתי בכתב יד למישהו וצלמו אותו','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('צאו לטיול רגלי של שעה במקום חדש וצלמו סלפי','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('הכינו ארוחת בוקר מפנקת למישהו וצלמו','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('עשו מדיטציה של 15 דקות וצלמו את המקום שבחרתם','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('נסו מתכון בריא חדש וצלמו את התוצאה','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('עשו 100 קפיצות בחבל (בסטים) וצלמו סרטון','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{video}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('קומו שעה מוקדם יותר ונצלו את הזמן — צלמו מה עשיתם','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('צרו משהו יצירתי במשך 30 דקות וצלמו סרטון','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{video}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('בשלו ארוחה למישהו שאכפת לכם ממנו וצלמו','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('עשו 20 דקות ריקוד רצוף וצלמו סרטון','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{video}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('למדו כישור קטן חדש מסרטון והדגימו במצלמה','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{video}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('צאו לשחות או לבריכה וצלמו סלפי אחרי','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('סדרו את כל השולחן/הארון עד שיבריק — לפני ואחרי','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('הכינו רשימת מטרות לחודש הקרוב וצלמו אותה','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('הכינו לחם או מאפה מבצק וצלמו את התוצאה','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'hard',10,40,'{photo}','pretty_spontaneous','אתגר אמיתי שדורש מאמץ — 10 נקודות.'),
('הכינו פיצה מאפס — בצק וכל — וצלמו את התוצאה','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{photo}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('נסעו למקום רחוק שלא הייתם בו וצלמו שם סלפי','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{photo}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('קומו לזריחה וצלמו אותה','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{photo}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('צאו לסיבוב לבד ב-22:00 בלילה וצלמו את הרגע','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{photo}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('העבירו 3 שעות בלי מסכים — צלמו סלפי לפני ואחרי','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{photo}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('צלמו את עצמכם לפני ואחרי אתגר + סרטון קצר איך הרגשתם','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{video}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('דברו מול המצלמה 2 דקות על מה שאתם הכי גאים בו','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{video}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('עשו משהו שתמיד פחדתם לעשות וצלמו סרטון אחרי','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{video}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('תכננו הפתעה למישהו וצלמו את התגובה שלו','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{video}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('בלו יום שלם בלי לקנות כלום וצלמו סלפי בסופו','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{photo}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('צאו לטיול ספונטני ליעד אקראי וצלמו סלפי שם','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{photo}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('עזרו לזר במשך שעה וספרו במצלמה איך היה','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{video}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('כתבו 10 דברים שאתם אסירי תודה עליהם וקראו במצלמה','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{video}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('עשו אימון קשה של 45 דקות וצלמו את עצמכם בסיום','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{video}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('בשלו ארוחה מלאה של שלוש מנות וצלמו את השולחן','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{photo}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('טבלו במים קרים וצלמו סרטון של הרגע','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{video}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('צאו לצפות בכוכבים בלילה וצלמו את השמיים','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{photo}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('עשו מעשה טוב אנונימי למישהו וספרו במצלמה','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{video}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('העבירו יום «כמו תייר» בעיר שלכם וצלמו 3 רגעים','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{photo}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('הזמינו מישהו למפגש או דייט וצלמו סלפי מהמקום','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{photo}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('הגיעו לנקודה הגבוהה ביותר בסביבה וצלמו את הנוף','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{photo}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('התנתקו מהרשתות ל-24 שעות וצלמו סלפי לפני ואחרי','צלמו ותעדו — צרפו תמונה כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{photo}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('הכינו סרטון של 60 שניות שמסכם שבוע בחייכם','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{video}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('עשו מעשה אומץ — שירו או דברו בפומבי — וצלמו','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{video}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.'),
('כתבו מכתב לעצמכם בעוד שנה וצלמו את עצמכם מקריאים משפט ממנו','תעדו את הרגע — צרפו סרטון קצר כהוכחה.',(select id from mission_categories where slug='general'),'extreme',20,80,'{video}','crazy','יציאה גדולה מאזור הנוחות — 20 נקודות.');
